export const Paths = {
  HOME: "/",
  USERS: "/users",
  USERS_CREATE: "/users/create",
  USERS_DETAILS_ID: "/users/details/:id",
  ADMIN_ROLES_CREATE: "/admin-roles/create",
  ADMIN_ROLES_DETAILS_ID: "/admin-roles/details/:id",
  PROFILE: "/profile",
  ADMIN_ROLES: "/admin-roles",
  SUBSCRIPTIONS: "/subscriptions",
  WEBSITE_ANALYTICS: "/website-analytics",
  STOCK_ANALYSES: "/stock-analyses",
  STOCK_REPORT: "/stock-report",
  TOP_HALAL_STOCKS: "/top-halal-stocks",
  PORTFOLIOS: "/portfolios",
  FINANCE: "/finance",
  ARTICLES: "/articles",
  ARTICLES_CREATE: "/articles-create",
  ARTICLES_CREATE_ID: "/articles-create/:id",
  WEBINARS: "/webinars",
  WEBINARS_CREATE: "/webinars-create",
  SUPPORT_TICKETS: "/support-tickets",
  NOTIFICATIONS: "/notifications",
  NOTIFICATIONS_CREATE: "/notifications-create",
  NOTIFICATIONS_DETAILS_ID: "/notifications/details/:id",
  NOTIFICATIONS_SETTINGS: "/notifications-settings",
  SETTINGS: "/settings",
  NOT_FOUND: "*",
  LOGIN: "/login",
  SIGN_UP: "/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  CHECK_YOUREMAIL: "/check-your-email",
  SET_NEW_PASSWORD: "/set-new-password",
  PASSWORD_RESET: "/password-reset",
  PERSONAL_INFO: "/personal-info",
  REPORT_DETAIL_ID: "/report-detail/:id",
  ARTICLE_DETAIL_ID: "/article-detail/:id",
  WEBINAR_DETAIL_ID: "/webinar-detail/:id",
  CREATE_REPORT: "/create-report",
  ACADEMY: "/academy",
  COURSE_INFO_ID: "/course-info/:id",
  MARKET_NEWS: "/market-news",
  SCREENING: "/screening",
  INSIDER_BY_SECTOR: "/insider-by-sector",
  DIVIDEND: "/dividend",
  INVESTING_CALCULATOR: "/investing-calculator",
  MY_PORTFOLIO: "/my-portfolio",
  PORTFOLIO_TRACKING: "/portfolio-tracking",
  PORTFOLIO_BACKTESTING: "/portfolio-backtesting",
  WEBINARS_CREATE_ID: "/webinars-create/:id",
  COURSES_CREATE_ID: "/courses-create/:id",
  COURSES_DETAIL_ID: "/courses-detail/:id",
  COURSES_CREATE: "/courses-create",
  SUMMARY: "/summary",
};

export const PathGenerators = {
  USERS_DETAILS_ID: (id: string) => Paths.USERS_DETAILS_ID.replace(":id", id),
  ADMIN_ROLES_DETAILS_ID: (id: string) =>
    Paths.ADMIN_ROLES_DETAILS_ID.replace(":id", id),
  REPORT_DETAIL_ID: (id: string) => Paths.REPORT_DETAIL_ID.replace(":id", id),
  ARTICLE_DETAIL_ID: (id: string) => Paths.ARTICLE_DETAIL_ID.replace(":id", id),
  WEBINAR_DETAIL_ID: (id: string) => Paths.WEBINAR_DETAIL_ID.replace(":id", id),
  NOTIFICATIONS_DETAIL_ID: (id: string) =>
    Paths.NOTIFICATIONS_DETAILS_ID.replace(":id", id),
  COURSE_INFO_ID: (id: string) => Paths.COURSE_INFO_ID.replace(":id", id),
  ARTICLES_CREATE_ID: (id: string) =>
    Paths.ARTICLES_CREATE_ID.replace(":id", id),
  WEBINARS_CREATE_ID: (id: string) =>
    Paths.WEBINARS_CREATE_ID.replace(":id", id),
  COURSES_CREATE_ID: (id: string) => Paths.COURSES_CREATE_ID.replace(":id", id),
  COURSES_DETAIL_ID: (id: string) => Paths.COURSES_DETAIL_ID.replace(":id", id),
};
